### ISSUE TITLE
`ERR_INVALID_PROTOCOL` for http files in version 5.0.1

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/httpyac#210]
HTTP File:

``` http
###
# @name PowerAppsBearerChallenge
@PowerAppsCommonApiEndpoint = https://api.powerapps.com
@PowerAppsApiVersionLatest = 2021-02-01
GET {{PowerAppsCommonApiEndpoint}}
  /providers/microsoft.PowerApps
  /environments
  ?api-version={{PowerAppsApiVersionLatest}}
Authorization: Bearer

```

When executing using node:
```
$ npx httpyac@5.0.1 test.http --all
Please use request.options[...] instead of request[...] for setting Got Options (protocol). Support will be removed
https://api.powerapps.com/providers/microsoft.PowerApps/environments?api-version=2021-02-01 {        
  protocol: 'HTTP',
  url: 'https://api.powerapps.com/providers/microsoft.PowerApps/environments?api-version=2021-02-01',
  method: 'GET',
  options: {
    http2: undefined,
    cookieJar: CookieJar {
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: false,
      store: { idx: {} },
      prefixSecurity: 'silent',
      _cloneSync: [Function (anonymous)],
      _importCookiesSync: [Function (anonymous)],
      getCookiesSync: [Function (anonymous)],
      getCookieStringSync: [Function (anonymous)],
      getSetCookieStringsSync: [Function (anonymous)],
      removeAllCookiesSync: [Function (anonymous)],
      setCookieSync: [Function (anonymous)],
      serializeSync: [Function (anonymous)]
    }
  },
  headers: { Authorization: 'Bearer' },
  proxy: undefined
} RequestError: Protocol "HTTP" not supported. Expected "http:"
    at Request._makeRequest (C:\path\to\test_dir\node_modules\got\dist\source\core\index.js:1183:19)
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:http:96:10)
    at Request._makeRequest (C:\path\to\test_dir\node_modules\got\dist\source\core\index.js:1130:43)
    at async C:\path\to\test_dir\node_modules\got\dist\source\core\index.js:334:17 {
  code: 'ERR_INVALID_PROTOCOL',
  timings: undefined
}
RequestError: Protocol "HTTP" not supported. Expected "http:"
    at Request._makeRequest (C:\path\to\test_dir\node_modules\got\dist\source\core\index.js:1183:19)
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:http:96:10)
    at Request._makeRequest (C:\path\to\test_dir\node_modules\got\dist\source\core\index.js:1130:43)
    at async C:\path\to\test_dir\node_modules\got\dist\source\core\index.js:334:17 {
  code: 'ERR_INVALID_PROTOCOL',
  timings: undefined
}
```

**Comment by fredrikhr** [comment]
I noticed that if I replace all the variables with constants, the same error occurs:

```
###
# @name PowerAppsBearerChallenge
GET https://api.powerapps.com
  /providers/microsoft.PowerApps
  /environments
  ?api-version=2021-02-01
Authorization: Bearer
```

**Comment by AnWeber** [comment]
Did a great job. I wanted to optimize for me only briefly the display for RabbitMQ and thereby immediately made the whole project broken. Thanks for the hint.

**Comment by AnWeber** [comment]
This not well thought out commit was the cause: https://github.com/AnWeber/httpyac/commit/86c5932fbd9cdf6c2bbcb3d37347a24b7a107c6d. Github Action is publishing a v5.0.2

**Comment by fredrikhr** [comment]
Hmm still not working for v5.0.2:

```
$ npx httpyac@5.0.2 test.http --all
Please use request.options[...] instead of request[...] for setting Got Options (protocol). Support will be removed
https://api.powerapps.com/providers/microsoft.PowerApps/environments?api-version=2021-02-01 {
  protocol: 'HTTP',
  url: 'https://api.powerapps.com/providers/microsoft.PowerApps/environments?api-version=2021-02-01',
  method: 'GET',
  options: {
    http2: undefined,
    cookieJar: CookieJar {
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: false,
      store: { idx: {} },
      prefixSecurity: 'silent',
      _cloneSync: [Function (anonymous)],
      _importCookiesSync: [Function (anonymous)],
      getCookiesSync: [Function (anonymous)],
      getCookieStringSync: [Function (anonymous)],
      getSetCookieStringsSync: [Function (anonymous)],
      removeAllCookiesSync: [Function (anonymous)],
      setCookieSync: [Function (anonymous)],
      serializeSync: [Function (anonymous)]
    }
  },
  headers: { Authorization: 'Bearer' },
  proxy: undefined
} RequestError: Protocol "HTTP" not supported. Expected "http:"
    at Request._makeRequest (/mnt/c/Users/sr341/OneDrive - Troms Kraft/Dokumenter/httpyac/node_modules/got/dist/source/core/index.js:1183:19)
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:http:96:10)
    at Request._makeRequest (/mnt/c/Users/sr341/OneDrive - Troms Kraft/Dokumenter/httpyac/node_modules/got/dist/source/core/index.js:1130:43)
    at async /mnt/c/Users/sr341/OneDrive - Troms Kraft/Dokumenter/httpyac/node_modules/got/dist/source/core/index.js:334:17 {
  code: 'ERR_INVALID_PROTOCOL',
  timings: undefined
}
RequestError: Protocol "HTTP" not supported. Expected "http:"
    at Request._makeRequest (/mnt/c/Users/sr341/OneDrive - Troms Kraft/Dokumenter/httpyac/node_modules/got/dist/source/core/index.js:1183:19)
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:http:96:10)
    at Request._makeRequest (/mnt/c/Users/sr341/OneDrive - Troms Kraft/Dokumenter/httpyac/node_modules/got/dist/source/core/index.js:1130:43)
    at async /mnt/c/Users/sr341/OneDrive - Troms Kraft/Dokumenter/httpyac/node_modules/got/dist/source/core/index.js:334:17 {
  code: 'ERR_INVALID_PROTOCOL',
  timings: undefined
}
```

**Comment by AnWeber** [comment]
But I don't understand right now, a "simple" request works for me. Give me a moment, then I simply revert the commit from this morning.

**Comment by fredrikhr** [comment]
Ah, I hadn't yet updated node_modules, I had just run `npx httpyac@5.0.2` and thought that would just work

**Comment by AnWeber** [comment]
I have now removed the protocol property from http requests anyway. I found another error regarding OAuth2 configuration, I have corrected it now.

**Comment by fredrikhr** [comment]
I can confirm that everything now seems to work again.
