### ISSUE TITLE
OAuth2 flows fail in version 5.0.2

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/httpyac#211]
# HTTP File:
```
###
# @name PowerAppsClientCredentialsSession
@powerapps_clientId = {{$input Client ID}}
@powerapps_clientSecret = {{$password Client secret}}
@powerapps_tokenEndpoint = https://login.microsoftonline.com/{{$input Tenant ID}}/oauth2/v2.0/token
@powerapps_scope = https://service.powerapps.com//.default
@powerapps_useAuthorizationHeader = false
GET https://api.powerapps.com
  /providers/microsoft.PowerApps
  /environments
  ?api-version=2021-02-01
Authorization: oauth2 client powerapps

###
# @name PowerAppsDeviceCodeSession
@powerapps_clientId = 1950a258-227b-4e31-a9cf-717495945fc2
@powerapps_tokenEndpoint = https://login.microsoftonline.com/common/oauth2/v2.0/token
@powerapps_deviceCodeEndpoint = https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
@powerapps_scope = https://service.powerapps.com//.default
@powerapps_useAuthorizationHeader = false
GET https://api.powerapps.com
  /providers/microsoft.PowerApps
  /environments
  ?api-version=2021-02-01
Authorization: oauth2 device powerapps

```

Example http file above shows first a client_credentials OAuth flow, second one shows a device code authorization grant flow.

## `client_credentials`

```
$ npx httpyac send --name PowerAppsClientCredentialsSession test.http 
? Client ID
? Client secret
? Tenant ID

---------------------

POST https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token
accept: */*
accept-encoding: gzip, deflate, br
content-length: ...
content-type: application/x-www-form-urlencoded
user-agent: httpyac

grant_type=client_credentials&scope=https%3A%2F%2Fservice.powerapps.com%2F%2F.default&client_id={clientId}&client_secret={clientSecret}

HTTP/1.1 200  - OK
cache-control: no-store, no-cache
connection: close
content-length: ...
content-type: application/json; charset=utf-8
date: Mon, 28 Feb 2022 12:05:56 GMT
expires: -1
p3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
pragma: no-cache
set-cookie: ...
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-ms-ests-server: 2.1.12470.13 - NEULR2 ProdSlices
x-ms-request-id: ...

{"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"{accessToken}"}
https://api.powerapps.com/providers/microsoft.PowerApps/environments?api-version=2021-02-01 {
  protocol: 'HTTP',
  url: 'https://api.powerapps.com/providers/microsoft.PowerApps/environments?api-version=2021-02-01',
  method: 'GET',
  options: {
    http2: undefined,
    cookieJar: CookieJar {
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: false,
      store: { idx: {} },
      prefixSecurity: 'silent',
      _cloneSync: [Function (anonymous)],
      _importCookiesSync: [Function (anonymous)],
      getCookiesSync: [Function (anonymous)],
      getCookieStringSync: [Function (anonymous)],
      getSetCookieStringsSync: [Function (anonymous)],
      removeAllCookiesSync: [Function (anonymous)],
      setCookieSync: [Function (anonymous)],
      serializeSync: [Function (anonymous)]
    }
  },
  headers: { Authorization: 'oauth2 client powerapps' },
  proxy: undefined
} Error: empty url
    at Object.Dn [as exchange] (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:3:31068)
    at ie (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:441)
    at Function.perform (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:9976)
    at to (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:11437)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.Ii [as action] (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:10993)
Error: empty url
    at Object.Dn [as exchange] (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:3:31068)
    at ie (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:441)
    at Function.perform (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:9976)
    at to (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:11437)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.Ii [as action] (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:10993)
```

If I read the log output correctly, the process fails with the error `empty url` after the oauth flow has completed successfully.

## Device code authorization grant flow

```
$ npx httpyac send --name PowerAppsDeviceCodeSession test.http
? Client ID 1950a258-227b-4e31-a9cf-717495945fc2
? Tenant ID organizations

---------------------

POST https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
accept: */*
accept-encoding: gzip, deflate, br
content-length: 102
content-type: application/x-www-form-urlencoded
user-agent: httpyac

client_id=1950a258-227b-4e31-a9cf-717495945fc2&scope=https%3A%2F%2Fservice.powerapps.com%2F%2F.default

HTTP/1.1 200  - OK
cache-control: no-store, no-cache
connection: close
content-length: ...
content-type: application/json; charset=utf-8
date: Mon, 28 Feb 2022 12:11:45 GMT
expires: -1
p3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
pragma: no-cache
set-cookie: ...
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-ms-ests-server: 2.1.12470.13 - NEULR2 ProdSlices
x-ms-request-id: d03ec6df-1e75-4461-a110-4e2c2aa6ef00

{"user_code":"{userCode}","device_code":"{deviceCode}","verification_uri":"https://microsoft.com/devicelogin","expires_in":900,"interval":5,"message":"To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code {userCode} to authenticate."}

---------------------

POST https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
accept: */*
accept-encoding: gzip, deflate, br
content-length: 102
content-type: application/x-www-form-urlencoded
user-agent: httpyac

client_id=1950a258-227b-4e31-a9cf-717495945fc2&scope=https%3A%2F%2Fservice.powerapps.com%2F%2F.default

HTTP/1.1 200  - OK
cache-control: no-store, no-cache
connection: close
content-length: 473
content-type: application/json; charset=utf-8
date: Mon, 28 Feb 2022 12:11:45 GMT
expires: -1
p3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
pragma: no-cache
set-cookie: ...
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-ms-ests-server: 2.1.12470.13 - NEULR2 ProdSlices
x-ms-request-id: ...

{"user_code":"{userCode}","device_code":"{deviceCode}","verification_uri":"https://microsoft.com/devicelogin","expires_in":900,"interval":5,"message":"To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code {userCode} to authenticate."}
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code {userCode} to authenticate.
Verification_Uri: https://microsoft.com/devicelogin
User_Code: {userCode}
/mnt/c/Users/sr341/OneDrive - Troms Kraft/Dokumenter/httpyac/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: /tmp/httpyac-test/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe --copy
/tmp/httpyac-test/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe: Invalid argument
    at makeError (/tmp/httpyac-test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/tmp/httpyac-test/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.clipboard.write (file:///tmp/httpyac-test/node_modules/clipboardy/index.js:37:2)
    at async Object.w.setClipboard (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:29602)
    at async o (/tmp/httpyac-test/node_modules/httpyac/dist/index.js:116:6219) {
  shortMessage: 'Command failed with exit code 1: /tmp/httpyac-test/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe --copy',
  command: '/tmp/httpyac-test/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe --copy',
  escapedCommand: '"/tmp/httpyac-test/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe" --copy',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/tmp/httpyac-test/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe: Invalid argument',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Here the issue seems to be with clipboardy, I am investigating whether this issue only occurs on Windows

*Client ID: 1950a258-227b-4e31-a9cf-717495945fc2 used in the Device code flow is the public Client ID of the Microsoft Azure Management Shell. All other sensitive information has been stripped in the log output above.*

**Comment by fredrikhr** [comment]
Client credentials flow now seems to work again (v5.0.3)

**Comment by AnWeber** [comment]
do you have problems with the device_code flow in v5.0.3?

Sorry. I needed/wanted RabbitMQ implementation and released my changes too early. I should have merged the changes in the tag and created the release from there.

**Comment by AnWeber** [comment]
I wrapped the call and log.warn the error message
