### ISSUE TITLE
Problem accessing json reponse body

### ISSUE THREAD

**Issue by lcnittl** [AnWeber/httpyac#357]
I am using the VSCode httpyacs extension and encounter problems accessing values from json response bodies.

First a working example:

### Request

```http
# @name json
POST https://reqbin.com/echo/post/json HTTP/1.1
Content-Type: application/json
Accept: application/json
Content-Length: 81

{
  "Id": 78912,
  "Customer": "Jason Sweet",
  "Quantity": 1,
  "Price": 18.00
}

###

# @ref json
{{
  console.info("'json':", json);
  console.info("'json.success':", json.success);
  console.info("'jsonResponse.body':", jsonResponse.body);
  console.info("'jsonResponse.body.success':", jsonResponse.body.success);
}}
```

### Response body

```json
{
	"success": "true"
}
```

### Console

```con
INFO: 'json':
{"success":"true"}
INFO: 'json.success':
true
INFO: 'jsonResponse.body':
{"success":"true"}

INFO: 'jsonResponse.body.success':

```

Though I am not sure why `jsonResponse.body.success` is empty, this seems to work fine.

However, when using it with a limesurvey instance:

### Request

```http
# @name json
POST https://limesurvey.example/?r=admin/remotecontrol HTTP/2.0
Content-Type: application/json

{
  "method": "get_session_key",
  "params": {
    "username": "myusername",
    "password": "mysecretpw"
  },
  "id": 1
}

###

# @ref json
{{
  console.info("'json':", json);
  console.info("'json.success':", json.result);
  console.info("'jsonResponse.body':", jsonResponse.body);
  console.info("'jsonResponse.body.success':", jsonResponse.body.result);
}}
```

### Response

```json
{"id":2,"result":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","error":null}
```

### Console

```con
INFO: 'json':
{"id":2,"result":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","error":null}
INFO: 'json.success':
INFO: 'jsonResponse.body':
{"id":2,"result":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","error":null}
INFO: 'jsonResponse.body.success':

```

I fail to get the value of `result`

Is it possible that this has to do with the `null` value in `error`? Any ideas/workarounds?

**Comment by AnWeber** [comment]
body is the original body from got and of type string. To access ParsedJson you could `parsedBody`

```
console.info("'jsonResponse.body':", jsonResponse.parsedBody);
 console.info("'jsonResponse.body.success':", jsonResponse.parsedBody.success);
```

**Comment by lcnittl** [comment]
Thanks for your reply!

I see. Unfortunately, that again does work for the first case

### Request readout

```http
# @ref json
{{
  console.info("'json':", json);
  console.info("'json.success':", json.success);
  console.info("'jsonResponse.body':", jsonResponse.body);
  console.info("'jsonResponse.body.success':", jsonResponse.body.success);
  console.info("'jsonResponse.parsedBody':", jsonResponse.parsedBody);
  console.info("'jsonResponse.parsedBody.success':", jsonResponse.parsedBody.success);
}}
```

### Console

```con
INFO: 'json':
{"success":"true"}
INFO: 'json.success':
true
INFO: 'jsonResponse.body':
{"success":"true"}

INFO: 'jsonResponse.body.success':
INFO: 'jsonResponse.parsedBody':
{"success":"true"}
INFO: 'jsonResponse.parsedBody.success':
true

```

but again not for the second, where it even fails to obtain `jsonResponse.parsedBody`

### Request readout

```http
# @ref json
{{
  console.info("'json':", json);
  console.info("'json.success':", json.result);
  console.info("'jsonResponse.body':", jsonResponse.body);
  console.info("'jsonResponse.body.result':", jsonResponse.body.result);
  console.info("'jsonResponse.parsedBody':", jsonResponse.parsedBody);
  console.info("'jsonResponse.parsedBody.result':", jsonResponse.parsedBody.result);
}}
```

### Console

```con
INFO: 'json':
{"id":2,"result":"YaKkY_o5tinkCj04YSnBI7UwYOrQ1SVW","error":null}
INFO: 'json.success':
INFO: 'jsonResponse.body':
{"id":2,"result":"YaKkY_o5tinkCj04YSnBI7UwYOrQ1SVW","error":null}
INFO: 'jsonResponse.body.result':
INFO: 'jsonResponse.parsedBody':

```

Interestingly, `jsonResponse.parsedBody` is empty in this case.

### Log

```log
ERROR: TypeError - Cannot read properties of undefined (reading 'result')
TypeError: Cannot read properties of undefined (reading 'result')
	at global.<anonymous> (c:\Users\knittlfrac92\repos\git.maulide.univie.ac.at\JWOCS\surveys\scripts\testing.http:27:77)
	at B$ (c:\Users\knittlfrac92\.vscode\extensions\anweber.vscode-httpyac-5.8.2\dist\extension.js:191:43412)
	at Wv (c:\Users\knittlfrac92\.vscode\extensions\anweber.vscode-httpyac-5.8.2\dist\extension.js:191:46726)
	at Object.action (c:\Users\knittlfrac92\.vscode\extensions\anweber.vscode-httpyac-5.8.2\dist\extension.js:191:46052)
	at h$.<anonymous> (c:\Users\knittlfrac92\.vscode\extensions\anweber.vscode-httpyac-5.8.2\dist\extension.js:1:5703)
	at Generator.next (<anonymous>)
	at s (c:\Users\knittlfrac92\.vscode\extensions\anweber.vscode-httpyac-5.8.2\dist\extension.js:1:3004)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by AnWeber** [comment]
I currently get a HTTP403 from `reqbin.com`. parsedBody is currently only filled when I also get JSON. My example using httpbin works

```
# @name json
GET https://httpbin.org/json

###
# @name executor
# @forceRef json
{{
  console.info("'json':", json);
  console.info("'json.success':", json.result);
  console.info("'jsonResponse.body':", jsonResponse.body);
  console.info("'jsonResponse.parsedBody':", jsonResponse.parsedBody);
  console.info("'jsonResponse.parsedBody.result':", jsonResponse.parsedBody.slideshow);
}}
```

**Comment by lcnittl** [comment]
My examples with json responses not having a `null` value also work, sorry if that was not clear. But as it seems, as soon as there is `null` in the json response, it does not work anymore, like with this response:
```json
{"id":2,"result":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","error":null}
```

I am currently trying to find a public REST API that has `null` in its response body's json.

**Comment by lcnittl** [comment]
Hmm. It is working here:

```http
# @name json
GET https://webhook.site/96678803-723e-4c61-b654-551a4f0e95da

###
# @name executor
# @forceRef json
{{
  console.info("'json':", json);
  console.info("'json.result':", json.result);
  console.info("'jsonResponse.body':", jsonResponse.body);
  console.info("'jsonResponse.parsedBody':", jsonResponse.parsedBody);
  console.info("'jsonResponse.parsedBody.result':", jsonResponse.parsedBody.result);
}}
```

So probably it is a problem of the limesurvey API -- although I don't quite get why, because the response body looks just normal, in both cases:

Limesurvey:
```json
{"id":2,"result":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","error":null}
```

webhook.site:
```json
{"id":2,"result":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","error":null}
```

**Comment by lcnittl** [comment]
An interesting detail is that (in the VSCode HttpBook) the response printed below the cell is a single line in the case of Limesurvey
```json
{"id":2,"result":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","error":null}
```

and pretty formatted json in the case of webhook.site
```json
{
	"id": 2,
	"result": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"error": null
}
```

Which to me hints that there is a problem in parsing the response from the limesurvey instance. But no idea why that would be.

**Comment by lcnittl** [comment]
Alright, I think I dug out the issue. The server replies with `content-type: text/javascript;charset=UTF-8`, instead of `application/json`. Sorry for all the noise, should have checked the response headers more thoroughly earlier.

**Comment by AnWeber** [comment]
That explains it. In that case just convert it yourself with JSON.parse.  If necessary it could also be done globally with a custom plugin.
