### ISSUE TITLE
TypeError on Node 19

### ISSUE THREAD

**Issue by estensen** [AnWeber/httpyac#379]
Having some problems after installing Node 19. This worked before on Node 16
Using httpyac version 5.8.2

```http
# Refresh user token
POST xxx
Authorization: Bearer {{deviceToken}}

{{
  test.status(200);
  exports.userToken = response.body;
}}
```

```✓ response status equals to 200
TypeError [ERR_INVALID_THIS]: Value of "this" must be of type nullish or must be the global object
    at new NodeError (node:internal/errors:399:5)
    at global.cryptoThisCheck (node:internal/process/pre_execution:288:17)
    at get crypto [as crypto] (node:internal/util:564:9)
    at Iu (/usr/local/lib/node_modules/httpyac/dist/index.js:3:44002)
    at St (/usr/local/lib/node_modules/httpyac/dist/index.js:3:43777)
    at et (/usr/local/lib/node_modules/httpyac/dist/index.js:3:47009)
    at Object.action (/usr/local/lib/node_modules/httpyac/dist/index.js:3:46342)
    at b.<anonymous> (/usr/local/lib/node_modules/httpyac/node_modules/hookpoint/dist/index.js:1:3786)
    at Generator.next (<anonymous>)
    at d (/usr/local/lib/node_modules/httpyac/node_modules/hookpoint/dist/index.js:1:1162) {
  code: 'ERR_INVALID_THIS'
}
```

**Comment by AnWeber** [comment]
Thanks for the tip. I'll see what I can do there. To have the variables directly accessible, I create my own Global Context and add the NodeJs methods there. This explains quite well the ERR_INVALID_THIS. Let's see what all I have to adjust.

**Comment by AnWeber** [comment]
The local execution looks good now, but the unit tests still fail. This seems to be a bug of mockttp (https://github.com/httptoolkit/mockttp/issues/107) though. 
If it's not urgent, I won't make a separate release now, but update it with the next release. Transitionally the use of the Docker image would go (see https://httpyac.github.io/guide/installation_docker.html)

**Comment by estensen** [comment]
It's not urgent. I'm just pinning mode:16 in my pipelines. Thanks for taking a look 🙌

**Comment by AnWeber** [comment]
Hi I forgot about the issue. I released an update. Please retest it. It should be fixed. Thanks

**Comment by estensen** [comment]
Confirm that it works for node:18. Thanks for fixing it so quickly!
