### ISSUE TITLE
v6.3.0 Seems to have broken running on Linux Build Agent

### ISSUE THREAD

**Issue by FrankRua** [AnWeber/httpyac#415]
HttpTests were working about an hour or so ago, and is still working on my local machine fine but on my build server now I get

--------------------- /__w/12/s/HttpTests/HealthcheckController.http  --
expression lbDns throws error
ReferenceError: lbDns is not defined
    at global.<anonymous> (/__w/12/s/HttpTests/HealthcheckController.http:15:20)
    at Gt (/__w/12/s/node_modules/httpyac/dist/index.js:6:2186)
    at ao (/__w/12/s/node_modules/httpyac/dist/index.js:6:2752)
    at /__w/12/s/node_modules/httpyac/dist/index.js:6:5967
    at V (/__w/12/s/node_modules/httpyac/dist/index.js:2:29549)
    at Object.Ql [as action] (/__w/12/s/node_modules/httpyac/dist/index.js:6:5933)
    at qt.trigger (/__w/12/s/node_modules/hookpoint/dist/index.js:1:3229)
    at async U (/__w/12/s/node_modules/httpyac/dist/index.js:2:32106)
    at async Object.ia [as action] (/__w/12/s/node_modules/httpyac/dist/index.js:2:73495)
    at async p.trigger (/__w/12/s/node_modules/hookpoint/dist/index.js:1:3212)
##[error]Bash exited with code '1'.

Seems like the config file is not being recognize?

**Comment by AnWeber** [comment]
@FrankRua I will take a look at it. I use .env Files for configuration and it seems that I do not have this error.

**Comment by chenrui333** [comment]
yeah, broken the tests in the homebrew run, https://github.com/Homebrew/homebrew-core/pull/125801

build log, https://github.com/Homebrew/homebrew-core/actions/runs/4433712291/jobs/7779080834

**Comment by AnWeber** [comment]
@FrankRua @chenrui333 
I now understand why I have no problems with the latest release. My automated tests use the default environment and in VSCode the problem does not occur. The cause is probably because I forgot to apply the activeEnvironment [here](https://github.com/AnWeber/httpyac/commit/0a6097eb165ed069bd6ec39d332da6b1e7c6c9ed#diff-cb20cc281ab06c1764ecbd090887f08bffedca8f2163da0d778da68977bac0faL150).

**Comment by AnWeber** [comment]
@chenrui333 I am honored that it was included in homebrew. I think it's cool. Thanks. Did not know

**Comment by chenrui333** [comment]
Gonna try your fix now. Thanks!

**Comment by chenrui333** [comment]
confirmed the fix, 👍
