### ISSUE TITLE
TypeError Invalid URL with Httpyac v6

### ISSUE THREAD

**Issue by tricktron** [AnWeber/httpyac#434]
I have the following `test.http` file:

```javascript
@host=https://{{MI_HOST}}:{{MI_PORT}}
/*
Post to xxx should return a list of xxx
*/

POST /public/rest/xxx/xxx
Content-Type: application/xml

# payload removed
{{
    test.status(200);
    test.hasResponseBody();
}}
```

which uses the following `test.env` file:

```console
MI_HOST=xxx-route-xxx-dev.xxx.ad.xxx.ch
MI_PORT=443
```

and gets executed with `httpyac -a -o short -e test`.

### Httpyac 5.10.2

Everything works.

### Httpyac 6.x (tested with all versions)

```javascript
{
  url: 'MI_HOST=xxx-route-xxx-dev.xxx.ad.xxx.ch',
  protocol: 'HTTP',
  method: 'GET',
  headers: {},
  body: 'MI_PORT=443',
  options: {
    cookieJar: CookieJar {
      rejectPublicSuffixes: undefined,
      enableLooseMode: false,
      allowSpecialUseDomain: true,
      store: { idx: {} },
      prefixSecurity: 'silent',
      _cloneSync: [Function (anonymous)],
      _importCookiesSync: [Function (anonymous)],
      getCookiesSync: [Function (anonymous)],
      getCookieStringSync: [Function (anonymous)],
      getSetCookieStringsSync: [Function (anonymous)],
      removeAllCookiesSync: [Function (anonymous)],
      setCookieSync: [Function (anonymous)],
      serializeSync: [Function (anonymous)]
    },
    hooks: { beforeRedirect: [Array], beforeRequest: [Array] }
  },
  proxy: undefined
}
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at Object.exports.default (/usr/local/lib/node_modules/httpyac/node_modules/got/dist/source/core/utils/options-to-url.js:35:17)
    at normalizeArguments (/usr/local/lib/node_modules/httpyac/node_modules/got/dist/source/core/index.js:486:51)
    at got (/usr/local/lib/node_modules/httpyac/node_modules/got/dist/source/create.js:112:39)
    at Wr.send (/usr/local/lib/node_modules/httpyac/dist/index.js:3:30896)
    at /usr/local/lib/node_modules/httpyac/dist/index.js:2:33618
    at Jo (/usr/local/lib/node_modules/httpyac/dist/index.js:2:31418)
    at Object.action (/usr/local/lib/node_modules/httpyac/dist/index.js:2:33609) {
  input: 'MI_HOST=xxx-route-xxx-dev.xxx.ad.xxx.ch',
  code: 'ERR_INVALID_URL'
}
```

### Hypothesis

A problem with parsing and normalising the given URL: `xxx-route-xxx-dev.xxx.ad.xxx.ch`

**Comment by AnWeber** [comment]
The glob pattern used is the cause. I explicitly do not specify a file extension to use and parse all files received. In this case the test.env file is executed as a request, because it also applies to glob `test`. Change your call to httpyac -a -o short -e *.http`
