### ISSUE TITLE
TypeError [ERR_INVALID_THIS]: Value of "this" must be of type nullish or must be the global object

### ISSUE THREAD

**Issue by simsurace** [AnWeber/httpyac#437]
I get this TypeError when running a simple GET request
```
$ httpyac send -a test.http
TypeError [ERR_INVALID_THIS]: Value of "this" must be of type nullish or must be the global object
    at new NodeError (node:internal/errors:399:5)
    at global.cryptoThisCheck (node:internal/process/pre_execution:286:17)
    at get crypto [as crypto] (node:internal/util:617:9)
    at sm (~/.npm-global/lib/node_modules/httpyac/dist/index.js:6:2490)
    at Gt (~/.npm-global/lib/node_modules/httpyac/dist/index.js:6:2268)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async xt (~/.npm-global/lib/node_modules/httpyac/dist/index.js:6:5619)
    at async p.trigger (~/.npm-global/lib/node_modules/httpyac/node_modules/hookpoint/dist/index.js:1:3212)
    at async Se.execute (~/.npm-global/lib/node_modules/httpyac/dist/index.js:2:49383)
    at async zd (~/.npm-global/lib/node_modules/httpyac/dist/index.js:119:29673) {
  code: 'ERR_INVALID_THIS'
}

---------------------
GET http://localhost:7777/healthz/live
accept: */*
accept-encoding: gzip, deflate, br
user-agent: httpyac

HTTP/1.1 200  - OK
transfer-encoding: chunked

Service is live
✓ status code Ok
```
where test.http reads

```
GET http://localhost:7777/healthz/live
{{
  const { equal } = require('assert');
  test('status code Ok', () => {
    equal(response.statusCode, 200);
  });
}}
```

**Comment by AnWeber** [comment]
@simsurace I think the error is related to the NodeJS version used. Which version is used? This was reported once before with #379, but I was able to work around it there.

**Comment by simsurace** [comment]
I was testing with 20. Will try with 18 then.
=
