### ISSUE TITLE
Using dynamic imports to import ESM does not work

### ISSUE THREAD

**Issue by utybo** [AnWeber/httpyac#445]
Hello! I'm trying to use `open` (https://www.npmjs.com/package/open), which is an ESM-only package. I've tried to use the [dynamic import feature](https://v8.dev/features/dynamic-import), but it's not working with a rather cryptic message.

Here's a repro script: 

```http
GET https://google.com

{{
    const open = await import("open");
    console.log("Hi!")
}}
```

And the stack trace:

```
ERROR: TypeError - A dynamic import callback was not specified.
TypeError: A dynamic import callback was not specified.
	at new NodeError (node:internal/errors:387:5)
	at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
	at c:\Users\MyUsername\work\http-playground\test.http:4:18
	at global.<anonymous> (c:\Users\MyUsername\work\http-playground\test.http:5:25)
	at RY (c:\Users\MyUsername\.vscode\extensions\anweber.vscode-httpyac-6.4.1\dist\extension.js:199:2219)
	at wb (c:\Users\MyUsername\.vscode\extensions\anweber.vscode-httpyac-6.4.1\dist\extension.js:199:5659)
	at Object.action (c:\Users\MyUsername\.vscode\extensions\anweber.vscode-httpyac-6.4.1\dist\extension.js:199:4923)
	at ste.trigger (c:\Users\MyUsername\.vscode\extensions\anweber.vscode-httpyac-6.4.1\dist\extension.js:1:5121)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async S1.execute (c:\Users\MyUsername\.vscode\extensions\anweber.vscode-httpyac-6.4.1\dist\extension.js:195:49063)
	at async pCr (c:\Users\MyUsername\.vscode\extensions\anweber.vscode-httpyac-6.4.1\dist\extension.js:312:29411)
	at async Object.ZQ (c:\Users\MyUsername\.vscode\extensions\anweber.vscode-httpyac-6.4.1\dist\extension.js:312:29300)
```

Is this a problem on httpyac's side, or is there something I did wrong? I'm using NodeJS 16. I've encountered the issue both via the VS Code extension *and* the CLI tool.

**Comment by AnWeber** [comment]
I think your mistake is related to #437. The cause should be that I created my own context, but did not explicitly add the import method. I now use the default context again as a fix and your error should also be fixed.

**Comment by AnWeber** [comment]
I still have the possibility to command supplemented `open`. I use it internally and can be used by `require("open")`. However still v8 (no esm). Please test the import of ESM Modules again with the new version. Thank you.
