### ISSUE TITLE
No file system provider exception

### ISSUE THREAD

**Issue by asampal** [AnWeber/httpyac#536]
I'm seeing this exception come up when an http editor is open:

```
Unavailable (FileSystemError): ENOPRO: No file system provider found for resource 'lottie:/?undefined'
	at k.e (c:\devenv\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:109:27276)
	at Object.stat (c:\devenv\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:109:24556)
	at async W$e.$t.io.fileProvider.readdir (c:\Users\asampaleanu\.vscode-insiders\extensions\anweber.vscode-httpyac-6.6.3\dist\extension.js:339:16594)
	at async c:\Users\asampaleanu\.vscode-insiders\extensions\anweber.vscode-httpyac-6.6.3\dist\extension.js:186:16097
	at async jq (c:\Users\asampaleanu\.vscode-insiders\extensions\anweber.vscode-httpyac-6.6.3\dist\extension.js:186:16361)
	at async FQ (c:\Users\asampaleanu\.vscode-insiders\extensions\anweber.vscode-httpyac-6.6.3\dist\extension.js:186:16026)
	at async bY.initHttpFile (c:\Users\asampaleanu\.vscode-insiders\extensions\anweber.vscode-httpyac-6.6.3\dist\extension.js:186:53878)
	at async bY.parse (c:\Users\asampaleanu\.vscode-insiders\extensions\anweber.vscode-httpyac-6.6.3\dist\extension.js:186:53453)
```

I don't have any Lottie-related extensions currently (I did at one time).

Windows 11, VSCode Insiders

**Comment by AnWeber** [comment]
@asampal I honestly don't understand. I can assure you that I don't have my extension file actively using lottie:/.... (whatever this extension does). I rather suspect that in your system the extension is still present. And sparks in between. In which use case does the error occur? The url looks strange to me with `lottie:/?undefined`.

**Comment by AnWeber** [comment]
There is a command `workbench.extensions.action.openExtensionsFolder`. Can you check ths folder if lottie extension still exists?

**Comment by asampal** [comment]
I reinstalled the Lottie extension and that seems to have fixed things for me, so closing.
