### ISSUE TITLE
Set variable if not set

### ISSUE THREAD

**Issue by barneyszabo439** [AnWeber/httpyac#583]
Hi,

I really like the project, thanks for making it and maintaining it! I was wondering about a feature that would really help me.

Context: I want to have a .HTTP file that I can use for both VS Code request sending and for use with the CLI in a pipeline. I want to have a variable that is set at the top of the .HTTP file using the `@myVariable=...` syntax. However I want it to be overridable via the CLI, using the `--var "myVariable=someothervalue"` syntax.

Basically:

```
@myVariable=foo

###
# @name myRequest
# @description Make a request
GET https://www.example.com/{{myVariable}}
```

If I call it using VS Code, it would do `GET https://www.example.com/foo`. However if I call using the CLI I should be able to do: `httpyac myfile.http -e dev --var "myVariable=bar"` which would then do `GET https://www.example.com/bar`.

I tried to do the null coalescing operator, i.e. `@myVariable={{myVariable ?? 'foo'}}` however it simply sets the value as `{{myVariable ?? 'foo'}}`.

Obviously this can be accomplished by using some JS, e.g. a `{{ ... }}` block at the top which checks if the value is undefined. However that is too long and it would be really nice if there was a shorthand for it.

It would be good if there was something like:

`@myVariable?=foo`

The `?=` would mean that:
- if `myVariable` is already set (truthsy), then do nothing
- if `myVariable` is not set then assign the value after

Would this be possible? Or am I missing a simpler way?

I'm using httpyac's CLI version 6.8.2.

P.S. Feel free to move this issue to one of the other repos if it's better suited there.

**Comment by AnWeber** [comment]
If you activate LogLevel Trace, you would see the reason. Your  variable `myVariable` is not defined anywhere, so JS throws a [ReferenceError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined?retiredLocale=de) 
```
DEBUG: variable myVariable ?? 'foo' not defined
DEBUG: ReferenceError - myVariable is not defined
ReferenceError: myVariable is not defined
	at Object.userJS (/home/andreas/github/httpyac/httpyac.github.io/examples/test.http:2:20)
	at runScript (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:146751:29)
	at evalExpression2 (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:146793:27)
	at /home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:147011:24
	at parseHandlebarsString (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:140416:31)
	at Object.replaceJavascriptExpressions [as action] (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:147009:20)
	at ReplaceVariableHook.trigger (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:4516:40)
	at async replaceVariables (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:139448:14)
	at async Object.action (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:142993:24)
	at async n.trigger (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:4516:23)
	at async _HttpRegion.execute (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:141664:26)
	at async sendHttpRegion (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:149709:16)
	at async Object.send4 (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:149698:18)
	at async DocumentStore.send (/home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:173855:24)
	at async /home/andreas/github/httpyac/vscode-httpyac/dist/extension.js:175902:11
```

Rewrite your code like this

```
@myVariable={{this.myVariable ?? 'foo'}}

GET https://httpbin.org/anything?foo={{myVariable}}
```
I'm not sure if I would insert a new syntax for this. It is already easy to solve using Javascript.

**Comment by barneyszabo439** [comment]
I'm quite happy with the `@myVariable={{this.myVariable ?? 'foo'}}` approach. While it's not as short as `@myVariable?='foo'`, it's still quite short (and certainly much better than what I had before). Thanks! Will close the issue.
