### ISSUE TITLE
Lowercase Method

### ISSUE THREAD

**Issue by rafaelhoff** [AnWeber/httpyac#588]
hi,

When following any example, like [springboot_actuator.http](https://github.com/httpyac/httpyac.github.io/blob/main/examples/api/springboot_actuator.http), if I try the method as lowercase, like `get /actuator/info` instead of `GET`, then I get a very strange error:

```
TypeError: Invalid URL
	at new NodeError (node:internal/errors:399:5)
	at URL.onParseError (node:internal/url:566:9)
	at new URL (node:internal/url:646:5)
	at X9.default (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:141:17742)
	at normalizeArguments (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:145:6685)
	at t (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:145:27968)
	at dir.send (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:193:46353)
	at /Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:192:19398
	at SMe (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:192:16457)
	at Object.action (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:192:19388)
	at async zee.trigger (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:26:3322)
	at async ZI.execute (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:192:51388)
	at async sLe (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:309:33383)
	at async Object.uY (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:309:33117)
	at async B6.send (/Users/user/.vscode/extensions/anweber.vscode-httpyac-6.10.0/dist/extension.js:345:28996)
	at async C.executeCell (/Users/user/.vscode/extensions/anweber.httpbook-3.2.3/dist/extension.js:1:7334)
	at async C.send (/Users/user/.vscode/extensions/anweber.httpbook-3.2.3/dist/extension.js:1:6982)
	at async c.$executeCells (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:103889)
```

is it expected that methods are always uppercase? if so, I guess this should be documented and a proper error displayed.

**Comment by AnWeber** [comment]
I changed it with https://github.com/AnWeber/httpyac/issues/447. I need to update docs. Thx for the hint. 
The error is thrown because method is not detected abd URL `get http://localhost` is used

**Comment by rafaelhoff** [comment]
thanks. I will update my files then. documentation would be good as well. Would be good as well if you could catch the error and validate against lowercase or enhance with the URL itself, then we could see that for example `TypeError: Invalid URL : get http://localhost/actuator/info`

**Comment by AnWeber** [comment]
I added a special error handling to output the used url.
