### ISSUE TITLE
CLI env not detected

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#65]
I have the following structure:
```
-- env
  |_ .env
  |_ prod.env               (API_URL=https://some.thing)
-- requests
  |_ something.http         (uses {{API_URL}})
-- package.json             (just script definitions)
```

When I run:
```sh
httpyac --env prod --all ./requests
```

I get:
```sh
ReplaceVariableHook: javascript failed
ExecuteHook: variableReplacer failed
ReferenceError: API_URL is not defined
    at Object.<anonymous> (requests/something.http:6:20)
    at Object.<anonymous> (~/.nvm/versions/node/v16.5.0/lib/node_modules/httpyac/dist/index.js:1:141494)
    at Generator.next (<anonymous>)
    at ~/.nvm/versions/node/v16.5.0/lib/node_modules/httpyac/dist/index.js:1:139999
    at new Promise (<anonymous>)
    at r (~/.nvm/versions/node/v16.5.0/lib/node_modules/httpyac/dist/index.js:1:139744)
    at Object.t.runScript ~/.nvm/versions/node/v16.5.0/lib/node_modules/httpyac/dist/index.js:1:141083)
    at Object.<anonymous> (~/.nvm/versions/node/v16.5.0/lib/node_modules/httpyac/dist/index.js:1:165669)
    at Generator.next (<anonymous>)
    at ~/.nvm/versions/node/v16.5.0/lib/node_modules/httpyac/dist/index.js:1:165188
```

It used to work before as far as I remember. And the environment is still correctly picked up by the vscode extension (and everything runs fine there). It's just the CLI which no longer works.

I'm using httpyac `v3.1.0` (unfortunately I don't remember what version it used to work on but I'm pretty sure I haven't changed my directory structure since it last worked). 🤔

**Comment by AnWeber** [comment]
The environment was unfortunately not passed correctly by the cli in to the logic adapted for the extension. 
The bug will be fixed with the next version.
